export { default as eqGray1 } from './gray/eq-gray-1.png';
export { default as eqGray2 } from './gray/eq-gray-2.png';
export { default as eqGray3 } from './gray/eq-gray-3.png';
export { default as eqGray4 } from './gray/eq-gray-4.png';
export { default as eqGray5 } from './gray/eq-gray-5.png';
export { default as eqGray6 } from './gray/eq-gray-6.png';
export { default as eqGray7 } from './gray/eq-gray-7.png';
export { default as eqGray8 } from './gray/eq-gray-8.png';
export { default as eqGray9 } from './gray/eq-gray-9.png';

export { default as eqGreen1 } from './green/eq-green-1.png';
export { default as eqGreen2 } from './green/eq-green-2.png';
export { default as eqGreen3 } from './green/eq-green-3.png';
export { default as eqGreen4 } from './green/eq-green-4.png';
export { default as eqGreen5 } from './green/eq-green-5.png';
export { default as eqGreen6 } from './green/eq-green-6.png';
export { default as eqGreen7 } from './green/eq-green-7.png';
export { default as eqGreen8 } from './green/eq-green-8.png';
export { default as eqGreen9 } from './green/eq-green-9.png';

export { default as eqBlue1 } from './blue/eq-blue-1.png';
export { default as eqBlue2 } from './blue/eq-blue-2.png';
export { default as eqBlue3 } from './blue/eq-blue-3.png';
export { default as eqBlue4 } from './blue/eq-blue-4.png';
export { default as eqBlue5 } from './blue/eq-blue-5.png';
export { default as eqBlue6 } from './blue/eq-blue-6.png';
export { default as eqBlue7 } from './blue/eq-blue-7.png';
export { default as eqBlue8 } from './blue/eq-blue-8.png';
export { default as eqBlue9 } from './blue/eq-blue-9.png';

export { default as eqPurple1 } from './purple/eq-purple-1.png';
export { default as eqPurple2 } from './purple/eq-purple-2.png';
export { default as eqPurple3 } from './purple/eq-purple-3.png';
export { default as eqPurple4 } from './purple/eq-purple-4.png';
export { default as eqPurple5 } from './purple/eq-purple-5.png';
export { default as eqPurple6 } from './purple/eq-purple-6.png';
export { default as eqPurple7 } from './purple/eq-purple-7.png';
export { default as eqPurple8 } from './purple/eq-purple-8.png';
export { default as eqPurple9 } from './purple/eq-purple-9.png';

export { default as eqGold1 } from './gold/eq-gold-1.png';
export { default as eqGold2 } from './gold/eq-gold-2.png';
export { default as eqGold3 } from './gold/eq-gold-3.png';
export { default as eqGold4 } from './gold/eq-gold-4.png';
export { default as eqGold5 } from './gold/eq-gold-5.png';
export { default as eqGold6 } from './gold/eq-gold-6.png';
export { default as eqGold7 } from './gold/eq-gold-7.png';
export { default as eqGold8 } from './gold/eq-gold-8.png';
export { default as eqGold9 } from './gold/eq-gold-9.png';
