import { FC } from 'react';

import {
    ContractorCabin,
    EquipmentSetPage,
    HomePage,
    MiningPage,
    ContractorStatsAndInfoPage,
    MineOwnerStatAndInfoPage,
    LandLordPage,
    HivePage,
    PageNotFound,
    MineManagementPage,
    MineOwnerPage,
    MineOwnerMiningCrewPage,
    InfoPage,
    Warehouse,
    ServiceMarketPage,
    AreaManagementPage,
    CreateOrderPage,
    LandlordStatsAndInfoPage,
    OperationPage,
    NftPreviewPage,
    AuthPage,
} from 'pages';

import {
    contractorCabin,
    equipmentSet,
    home,
    intro,
    mineManagement,
    mineOwner,
    mining,
    pageNotFound,
    root,
    wipPage,
    contractorStatsAndInfo,
    mineOwnerStatsAndInfo,
    mineOwnerMineCrew,
    landLord,
    serviceMarket,
    hive,
    user,
    warehouse,
    areaManagement,
    createOrder,
    serviceMarketOrder,
    landLordStats,
    inventoryItemPreview,
} from './paths';

export type AppRoute = {
    titleTag: string;
    path: string;
    Component: FC;
    forLoggedIn?: boolean;
    forAdmin?: boolean;
    forBetaUser?: boolean;
};

export const routes: AppRoute[] = [
    {
        path: root,
        Component: AuthPage,
        titleTag: 'Intro - Deepmine',
    },
    {
        path: intro,
        Component: AuthPage,
        titleTag: 'Intro - Deepmine',
    },
    {
        path: contractorCabin,
        Component: ContractorCabin,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Contractor — DeepMine',
    },
    {
        path: equipmentSet,
        Component: EquipmentSetPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Equipment set — DeepMine',
    },
    {
        path: home,
        Component: HomePage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Hometown — DeepMine',
    },
    {
        path: mining,
        Component: MiningPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Mining — DeepMine',
    },
    {
        path: mineOwner,
        Component: MineOwnerPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Mine owner cabin — DeepMine',
    },
    {
        path: mineManagement,
        Component: MineManagementPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Mine management — DeepMine',
    },
    {
        path: contractorStatsAndInfo,
        Component: ContractorStatsAndInfoPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Contractor / Stats and Info',
    },
    {
        path: mineOwnerStatsAndInfo,
        Component: MineOwnerStatAndInfoPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Mine owner / Stats and Info',
    },
    {
        path: mineOwnerMineCrew,
        Component: MineOwnerMiningCrewPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Mine owner / Mine crew',
    },
    {
        path: pageNotFound,
        Component: PageNotFound,
        forLoggedIn: false,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Badlands — DeepMine',
    },
    {
        path: wipPage,
        Component: () => <PageNotFound type="wip" />,
        forLoggedIn: false,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Badlands — DeepMine',
    },
    {
        path: serviceMarket,
        Component: ServiceMarketPage,
        forLoggedIn: false,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Service-market — DeepMine',
    },
    {
        path: serviceMarketOrder,
        Component: OperationPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Service-market — DeepMine',
    },
    {
        path: landLord,
        Component: LandLordPage,
        forLoggedIn: false,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Landlord — DeepMine',
    },
    {
        path: landLordStats,
        Component: LandlordStatsAndInfoPage,
        forLoggedIn: false,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Landlord — DeepMine',
    },
    {
        path: areaManagement,
        Component: AreaManagementPage,
        forLoggedIn: false,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Landlord — Area management',
    },
    {
        path: hive,
        Component: HivePage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Hive — DeepMine',
    },
    {
        path: user,
        Component: InfoPage,
        forLoggedIn: false,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Hive — DeepMine',
    },
    {
        path: warehouse,
        Component: Warehouse,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Warehouse — DeepMine',
    },
    {
        path: createOrder,
        Component: CreateOrderPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Create order — DeepMine',
    },
    {
        path: inventoryItemPreview,
        Component: NftPreviewPage,
        forLoggedIn: true,
        forAdmin: true,
        forBetaUser: true,
        titleTag: 'Card preview — DeepMine',
    },
];

export const fallbackRoute: AppRoute = {
    path: '*',
    Component: PageNotFound,
    titleTag: 'Intro - Deepmine',
};
